import numpy as np
from scipy.spatial import Voronoi
import heapq
import random
from coordinate_system import terrain_shape

def load_plotter_context():
    data = np.load('data/settlement_data.npz', allow_pickle=True)
    core_data = np.load('data/settlement_core.npz', allow_pickle=True)
    viz = np.load('data/settlement_viz.npz', allow_pickle=True)

    return {
        'seeds': data['seeds'],
        'heightmap': data['heightmap'],
        'core_indices': set(core_data['core_indices'].tolist()),
        'blocks': viz['blocks'].copy(),
        'palette': viz['palette'].tolist(),
        'origin': viz['origin'],
        'meta': viz['meta']
    }


def largest_rectangle_in_mask(mask):
    """
    Find the largest axis-aligned rectangle of True cells in a 2D mask.

    The mask is stored as [z, x]. Returns a dict with local coordinates:
        x, z, width, depth, area
    or None when no True rectangle exists.
    """
    if mask.size == 0 or not np.any(mask):
        return None

    depth, width = mask.shape
    heights = np.zeros(width, dtype=int)
    best = None

    for z in range(depth):
        heights = np.where(mask[z], heights + 1, 0)
        stack = []

        for x in range(width + 1):
            current_height = heights[x] if x < width else 0
            while stack and heights[stack[-1]] > current_height:
                height = heights[stack.pop()]
                left = stack[-1] + 1 if stack else 0
                rect_width = x - left
                area = rect_width * height
                if best is None or area > best["area"]:
                    best = {
                        "x": int(left),
                        "z": int(z - height + 1),
                        "width": int(rect_width),
                        "depth": int(height),
                        "area": int(area),
                    }
            stack.append(x)

    return best


def build_cell_mask(seeds, hmap, cell_idx, setback=0.0):
    """Return a [z, x] mask for buildable cells inside one Voronoi region."""
    W, D = terrain_shape(hmap)
    vor = Voronoi(seeds)
    region = vor.regions[vor.point_region[cell_idx]]
    if -1 in region or len(region) == 0:
        return None

    vertices = vor.vertices[region]
    cell_ridges = []
    for i in range(len(region)):
        v1 = vor.vertices[region[i]]
        v2 = vor.vertices[region[(i + 1) % len(region)]]
        cell_ridges.append((v1, v2))

    min_x = max(0, int(np.floor(np.min(vertices[:, 0]))))
    max_x = min(W - 1, int(np.ceil(np.max(vertices[:, 0]))))
    min_z = max(0, int(np.floor(np.min(vertices[:, 1]))))
    max_z = min(D - 1, int(np.ceil(np.max(vertices[:, 1]))))

    mask = np.zeros((D, W), dtype=bool)
    for x in range(min_x, max_x + 1):
        for z in range(min_z, max_z + 1):
            if np.argmin(np.linalg.norm(seeds - [x, z], axis=1)) != cell_idx:
                continue

            if setback > 0:
                p_curr = np.array([x, z])
                too_close = False
                for vr1, vr2 in cell_ridges:
                    l2 = np.sum((vr1 - vr2) ** 2)
                    if l2 == 0:
                        continue
                    t = max(0, min(1, np.dot(p_curr - vr1, vr2 - vr1) / l2))
                    if np.linalg.norm(p_curr - (vr1 + t * (vr2 - vr1))) < setback:
                        too_close = True
                        break
                if too_close:
                    continue

            mask[z, x] = True

    return mask


def largest_buildable_rectangle_from_data(seeds, hmap, cell_idx, setback=3.0, origin=None):
    mask = build_cell_mask(seeds, hmap, cell_idx, setback=setback)
    rect = largest_rectangle_in_mask(mask) if mask is not None else None
    if rect is None:
        return None

    height_region = hmap[
        rect["z"] : rect["z"] + rect["depth"],
        rect["x"] : rect["x"] + rect["width"],
    ]
    rect["y"] = int(np.max(height_region))
    rect["height_min"] = int(np.min(height_region))
    rect["height_max"] = int(np.max(height_region))
    rect["cell_id"] = int(cell_idx)
    if origin is not None:
        rect["world_x"] = int(origin[0] + rect["x"])
        rect["world_z"] = int(origin[2] + rect["z"])
    return rect


def largest_buildable_rectangle_for_cell(cell_idx, setback=3.0):
    """
    Return the largest axis-aligned build rectangle inside one Voronoi cell.

    Coordinates are local to the stored settlement slice. The returned dict:
        x, z, width, depth, area, y, cell_id
    describes the footprint [x:x+width, z:z+depth].
    """
    ctx = load_plotter_context()
    return largest_buildable_rectangle_from_data(
        ctx['seeds'],
        ctx['heightmap'],
        cell_idx,
        setback=setback,
        origin=ctx['origin'],
    )

def visualize_house_volumes(module_size=7, max_floors=3):
    # 1. LOAD PLOTS
    # We load the plots generated by the find_modular_plots_with_setback function
    plot_data = np.load('data/settlement_plots.npz', allow_pickle=True)
    plots = dict(plot_data['plots'])

    viz = np.load('data/settlement_viz.npz', allow_pickle=True)
    blocks = viz['blocks'].copy()
    palette = viz['palette'].tolist()
    hmap = np.load('data/settlement_data.npz')['heightmap']

    # 2. DEFINE MATERIALS
    def get_id(name):
        if name not in palette: palette.append(name)
        return palette.index(name)

    # Different colors for different floors to visualize the hierarchy
    COLORS = [
        get_id("minecraft:red_wool"), # 1st Floor
        get_id("minecraft:terracotta"),    # 2nd Floor
        get_id("minecraft:yellow_concrete")   # 3rd Floor
    ]

    for cell_id, modules in plots.items():
        if not modules: continue

        # Convert modules to a set for fast adjacency lookup
        module_set = set(modules)

        # We store the floor level for each module coordinate
        # floor_map[(mx, mz)] = current_height_in_modules
        floor_map = {m: 1 for m in modules}

        # 3. CALCULATE STACKING (Connectivity Rule)
        # We iterate up to max_floors
        for floor in range(1, max_floors):
            for mx, mz in modules:
                # Only try to stack if this module reached the previous floor
                if floor_map[(mx, mz)] == floor:
                    # Check 4 cardinal neighbors on the current floor level
                    neighbors = 0
                    for dx, dz in [(module_size, 0), (-module_size, 0), (0, module_size), (0, -module_size)]:
                        if (mx + dx, mz + dz) in floor_map:
                            # Does the neighbor also have this floor level?
                            if floor_map[(mx + dx, mz + dz)] >= floor:
                                neighbors += 1

                    # RULE: If connected to > 2 modules, add a floor
                    if neighbors > 2:
                        floor_map[(mx, mz)] += 1

        # 4. DRAW VOLUMES
        for (mx, mz), floor_count in floor_map.items():
            base_y = int(hmap[mz, mx])

            for f in range(floor_count):
                # Each floor is 4 blocks high
                y_start = base_y + (f * module_size) + 1 # +1 to stay above foundation
                y_end = y_start + module_size

                # Draw the modular box
                # Leave 1 block gap between modules for visual "seams"
                blocks[mx:mx+module_size, y_start:y_end, mz:mz+module_size] = COLORS[random.randint(0, 2)]

    # 5. SAVE
    np.savez('data/settlement_viz.npz', blocks=blocks, palette=np.array(palette),
             origin=viz['origin'], meta=viz['meta'])
    print(f"House volumes visualized with up to {max_floors} floors.")

def find_modular_plots(
    module_size=7,
    setback=3.0,
    farm_setback=2.0,
    min_build_width=0,
    min_build_depth=0,
):
    """
    setback: distance for houses (usually larger to account for eaves/porches)
    farm_setback: distance for farm borders from path centerlines
    min_build_width/min_build_depth: drop building rectangles smaller than this
        footprint (0 disables the filter, preserving the original behaviour).
    """
    ctx = load_plotter_context()
    seeds, hmap, core_indices = ctx['seeds'], ctx['heightmap'], ctx['core_indices']
    blocks, palette = ctx['blocks'], ctx['palette']
    W, D = terrain_shape(hmap)
    vor = Voronoi(seeds)

    def get_id(name):
        if name not in palette: palette.append(name)
        return palette.index(name)

    HOUSE_MARKER = get_id("minecraft:terracotta")
    FARM_SOIL = get_id("minecraft:dirt_path")
    FARM_CROP = get_id("minecraft:lime_concrete")

    plotted_houses = {}
    farm_plots = {}
    building_rects = {}

    for p_idx in core_indices:
        region_idx = vor.point_region[p_idx]
        region = vor.regions[region_idx]
        if -1 in region: continue

        v_coords = vor.vertices[region]
        cell_ridges = []
        for i in range(len(region)):
            v1, v2 = vor.vertices[region[i]], vor.vertices[region[(i + 1) % len(region)]]
            cell_ridges.append((v1, v2))

        # 1. HOUSE MODULE CALCULATION
        min_x, max_x = int(np.min(v_coords[:, 0])), int(np.max(v_coords[:, 0]))
        min_z, max_z = int(np.min(v_coords[:, 1])), int(np.max(v_coords[:, 1]))

        grid_x_start = (min_x // module_size) * module_size
        grid_z_start = (min_z // module_size) * module_size

        valid_modules = []
        for ax in range(grid_x_start, max_x + 1, module_size):
            for az in range(grid_z_start, max_z + 1, module_size):
                is_valid = True
                for ox in range(module_size):
                    for oz in range(module_size):
                        cx, cz = ax + ox, az + oz
                        if not (0 <= cx < W and 0 <= cz < D) or \
                           np.argmin(np.linalg.norm(seeds - [cx, cz], axis=1)) != p_idx:
                            is_valid = False; break

                        p_curr = np.array([cx, cz])
                        for vr1, vr2 in cell_ridges:
                            l2 = np.sum((vr1 - vr2)**2)
                            if l2 == 0: continue
                            t = max(0, min(1, np.dot(p_curr - vr1, vr2 - vr1) / l2))
                            if np.linalg.norm(p_curr - (vr1 + t * (vr2 - vr1))) < setback:
                                is_valid = False; break
                        if not is_valid: break
                    if not is_valid: break
                if is_valid: valid_modules.append((ax, az))

        # 2. CLASSIFICATION & DRAWING
        if len(valid_modules) >= 4:
            rect = largest_buildable_rectangle_from_data(
                seeds,
                hmap,
                p_idx,
                setback=setback,
                origin=ctx['origin'],
            )
            if (
                rect is not None
                and rect["width"] >= min_build_width
                and rect["depth"] >= min_build_depth
            ):
                building_rects[p_idx] = rect
            plotted_houses[p_idx] = valid_modules
            for mx, mz in valid_modules:
                y = int(hmap[mz, mx])
                blocks[mx:mx+module_size, y, mz:mz+module_size] = HOUSE_MARKER
        else:
            # Farm Logic with Setback
            farm_cells = []
            for x in range(min_x, max_x + 1):
                for z in range(min_z, max_z + 1):
                    if 0 <= x < W and 0 <= z < D:
                        if np.argmin(np.linalg.norm(seeds - [x, z], axis=1)) == p_idx:
                            p_curr = np.array([x, z])

                            # Calculate distance to nearest ridge to respect the path
                            min_dist = float('inf')
                            for vr1, vr2 in cell_ridges:
                                l2 = np.sum((vr1 - vr2)**2)
                                if l2 == 0: continue
                                t = max(0, min(1, np.dot(p_curr - vr1, vr2 - vr1) / l2))
                                dist = np.linalg.norm(p_curr - (vr1 + t * (vr2 - vr1)))
                                min_dist = min(min_dist, dist)

                            # Only paint if we are outside the farm_setback
                            if min_dist >= farm_setback:
                                y = int(hmap[z, x])
                                farm_cells.append((x, z))
                                # If close to the farm edge (but safe from road), make it soil
                                if min_dist < farm_setback + 1.0:
                                    blocks[x, y, z] = FARM_SOIL
                                else:
                                    blocks[x, y, z] = FARM_CROP
            if farm_cells:
                farm_plots[p_idx] = farm_cells

    # 3. SAVE
    np.savez('data/settlement_viz.npz', blocks=blocks, palette=np.array(palette),
             origin=ctx['origin'], meta=ctx['meta'])
    np.savez(
        'data/settlement_plots.npz',
        plots=np.array(list(plotted_houses.items()), dtype=object),
        farms=np.array(list(farm_plots.items()), dtype=object),
        building_rects=np.array(list(building_rects.items()), dtype=object),
        module_size=np.array(module_size),
        setback=np.array(setback),
        farm_setback=np.array(farm_setback),
        min_build_width=np.array(min_build_width),
        min_build_depth=np.array(min_build_depth),
    )

if __name__ == "__main__":
    # With paths being 3 wide, setback=2.5 provides a nice small gutter/yard
    find_modular_plots(module_size=8, setback=2.5)
    visualize_house_volumes(module_size=8, max_floors=3)
