from __future__ import annotations
import os
from pathlib import Path

import requests

# --- .env loading ------------------------------------------------------------
# Judges: DO NOT edit this file. Put your key in the `.env` file at the repo
# root instead. We search from this module upward to the repo root, load the
# first `.env` found, and never overwrite a variable that is already set in the
# real environment (a real env var always wins).

def _load_dotenv() -> None:
    here = Path(__file__).resolve()
    for directory in (here.parent, *here.parents):
        candidate = directory / ".env"
        if not candidate.is_file():
            continue
        for raw_line in candidate.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:  # real env vars take precedence
                os.environ[key] = value
        break  # first .env found wins


_load_dotenv()

# --- Backend configuration ---------------------------------------------------
# Only two paths exist: the hosted (OpenAI-compatible) API, or offline fallback
# content. When no key is configured or the endpoint is unreachable, chat()
# raises LLMUnavailable and the narrative generators switch to fallback content.
# The endpoint is OpenAI-compatible, so any provider that speaks that protocol
# works by pointing LLM_API_BASE_URL / LLM_API_MODEL at it in your .env.
API_BASE_URL = os.environ.get("LLM_API_BASE_URL", "https://api.openai.com/v1")
API_MODEL = os.environ.get("LLM_API_MODEL", "gpt-4o-mini")
API_KEY = os.environ.get("LLM_API_KEY", "")  # comes from .env / environment only

# Backwards-compatible aliases (referenced by docs / older callers).
DEFAULT_BASE_URL = API_BASE_URL
DEFAULT_TIMEOUT = 30


class LLMUnavailable(RuntimeError):
    """Raised when the LLM backend cannot be used at all.

    Covers both "no key configured" and "the endpoint isn't reachable" (server
    down, port closed, request timed out). The narrative generators catch THIS
    to switch to offline fallback content (see fallback_content.py), while still
    letting genuine HTTP/parse errors surface as before.
    """


def chat(
    user_message: str,
    system_message: str = "You are a creative writer for a Minecraft settlement.",
    base_url: str | None = None,
    model: str | None = None,
    temperature: float = 0.7,
    max_tokens: int = 200,
    timeout: int = DEFAULT_TIMEOUT,
) -> str:
    if not API_KEY:
        raise LLMUnavailable(
            "No API key configured. Set LLM_API_KEY in the `.env` file at the "
            "repo root (and optionally LLM_API_BASE_URL / LLM_API_MODEL). "
            "Without a key the narrative uses offline fallback content."
        )

    resolved_base = base_url or API_BASE_URL
    resolved_model = model or API_MODEL
    headers = {"Authorization": f"Bearer {API_KEY}"}

    payload = {
        "model": resolved_model,
        "messages": [
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }
    try:
        r = requests.post(
            f"{resolved_base}/chat/completions",
            json=payload,
            headers=headers,
            timeout=timeout,
        )
    except (requests.ConnectionError, requests.Timeout) as exc:
        # "Not connected": server unreachable or hung. Re-raise as the typed
        # exception so generators can switch to offline fallback content.
        raise LLMUnavailable(
            f"LLM backend unreachable at {resolved_base}: {exc}"
        ) from exc
    r.raise_for_status()
    return r.json()["choices"][0]["message"]["content"].strip()
